services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pass123456"
    volumes:
      - sqlserver_data:/var/opt/mssql
  usersManagement:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: user_management
      POSTGRES_USER: user_management
      POSTGRES_PASSWORD: user_management
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
networks:
  my_network:
    driver: bridge

volumes:
  sqlserver_data:
  pgdata: